### ISSUE TITLE
Gradle build error after updating to 1.1.11 from 1.1.6

### ISSUE THREAD

**Issue by doniwinata0309** [johncarl81/parceler#355]
Hi,
I got this error after updating to parceler 1.1.11, while it is working fine on parceler 1.1.6

Android gradle plugin : 3.1.2
Kotlin: 1.2.40
androidSupport       : 27.1.1
Databinding compiler: 27.1.1

Here some error log from logcat and please let me know if you need additional information. do you know what might be wrong with this ? thank you

```
12:09:00.321 [ERROR] [system.err]   symbol:   class DataBindingComponent
12:09:00.321 [ERROR] [system.err]   location: class LayerViewDescriptionToolbarSearchContentBinding
12:09:00.322 [ERROR] [system.err] /Users/doni.winata/android-v3/app/build/generated/source/dataBinding/baseClasses/general/debug/com/test/android/databinding/LayerViewDescriptionToolbarSearchContentBinding.java:70: error: cannot find symbol
```

```
12:09:00.751 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException
12:09:00.751 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileGeneralDebugJavaWithJavac'.
12:09:00.752 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
12:09:00.753 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
12:09:00.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.Main.compile(Main.java:553)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:89)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
12:09:00.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:49)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:35)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:110)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:106)
12:09:00.756 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:59)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:43)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:153)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:121)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:125)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
12:09:00.757 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 33 more
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NullPointerException
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.base.Preconditions.checkNotNull(Preconditions.java:210)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.ImmutableList.of(ImmutableList.java:89)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.ImmutableList.copyOf(ImmutableList.java:273)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.ImmutableList.copyOf(ImmutableList.java:226)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.FluentIterable.toList(FluentIterable.java:373)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.adapter.GenericsUtil$1.buildGenericParameters(GenericsUtil.java:79)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.adapter.ASTGenericTypeWrapper.getGenericArgumentTypes(ASTGenericTypeWrapper.java:43)
12:09:00.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.adapter.GenericsUtil$1.buildGenericParameters(GenericsUtil.java:74)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.adapter.ASTGenericTypeWrapper.getGenericArgumentTypes(ASTGenericTypeWrapper.java:43)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.adapter.ASTGenericTypeWrapper.equals(ASTGenericTypeWrapper.java:162)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.util.matcher.ASTTypeMatcher.matches(ASTTypeMatcher.java:52)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.util.matcher.ASTTypeMatcher.matches(ASTTypeMatcher.java:26)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.Generators.matches(Generators.java:45)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.matcher.GenericCollectionMatcher$1.apply(GenericCollectionMatcher.java:49)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.matcher.GenericCollectionMatcher$1.apply(GenericCollectionMatcher.java:47)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.Iterators.all(Iterators.java:697)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.Iterables.all(Iterables.java:632)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.collect.FluentIterable.allMatch(FluentIterable.java:225)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.matcher.GenericCollectionMatcher.matches(GenericCollectionMatcher.java:47)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.matcher.GenericCollectionMatcher.matches(GenericCollectionMatcher.java:30)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.Generators.matches(Generators.java:45)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelableAnalysis.validateType(ParcelableAnalysis.java:649)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelableAnalysis.innerAnalyze(ParcelableAnalysis.java:315)
12:09:00.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelableAnalysis.analyze(ParcelableAnalysis.java:68)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:48)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:31)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.guava.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.TransactionProcessorPool.execute(TransactionProcessorPool.java:60)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.TransactionProcessorComposite.execute(TransactionProcessorComposite.java:37)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.transfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:38)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.internal.ParcelProcessor.execute(ParcelProcessor.java:83)
12:09:00.760 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.parceler.ParcelAnnotationProcessor.process(ParcelAnnotationProcessor.java:84)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.processing.IsolatingProcessor.process(IsolatingProcessor.java:50)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.Main.compile(Main.java:523)
12:09:00.761 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 64 more
12:09:00.761 [ERROR] [org.gradle.internal
``

**Comment by johncarl81** [comment]
Hmm, do you have a class that you've annotated with `@Parcel` that has generics defined?

**Comment by doniwinata0309** [comment]
Hi @johncarl81, does generic defined means is generic on the base class or generic on the field ?
We only have generic on the field: 
`protected LinkedHashMap<String, String> promo;`
this class annotated with @parcel and used as viewmodel for databinding.

**Comment by johncarl81** [comment]
Could you share the full details of that class?  I wonder if changing `LinkedHashMap<..>` to just `Map<...>` would make a difference.

**Comment by doniwinata0309** [comment]
This is the example of full class:

`@Parcel
public class TestParcel extends BaseObservable {

    protected LinkedHashMap<String, String> promo;

    public TestParcel() {
        promo = new LinkedHashMap<>();
    }


    @Bindable
    public LinkedHashMap<String, String> getPromo() {
        return promo;
    }

    public void setPromo(LinkedHashMap<String, String> promo) {
        this.promo = promo;
        notifyPropertyChanged(BR.promo);
    }

}
`
We use so many LinkedHashMap on the other class as well, do you think LinkedHashMap could be the problem here ?

**Comment by johncarl81** [comment]
Ah, I think it's tripping up on something in `BaseObservable`.   Would you try the following configuration:
```java
@Parcel(analyze = TestParcel.class)
public class TestParcel extends BaseObservable {

    protected LinkedHashMap<String, String> promo;

    public TestParcel() {
        promo = new LinkedHashMap<>();
    }

    @Bindable
    public LinkedHashMap<String, String> getPromo() {
        return promo;
    }

    public void setPromo(LinkedHashMap<String, String> promo) {
        this.promo = promo;
        notifyPropertyChanged(BR.promo);
    }

}
```

**Comment by johncarl81** [comment]
In general I opt for using the most general interface I can - typically using the interface over the implementation.  In this case `LinkedHashMap` is an implementation of `Map`.  Parceler [does handle `LinkedHashMap`](https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelerModule.java#L223) though, so that's not an issue.

**Comment by doniwinata0309** [comment]
I just added `analyze` on the top of the class but cannot see any difference from the log or error trace, what `analyze` use for ?

**Comment by johncarl81** [comment]
analyze is used to explicitly indicate which classes for Parceler to process ([Javadocs](https://oss.sonatype.org/service/local/repositories/releases/archive/org/parceler/parceler-api/1.1.11/parceler-api-1.1.11-javadoc.jar/!/index.html))

**Comment by doniwinata0309** [comment]
hi @johncarl81 , apologize for the late reply.
I just put all @Parcel annotation with analyze parameter, but the error remain the same.  do you have other suggestion ?

**Comment by doniwinata0309** [comment]
I just check the documentation again, is it mandatory for these points after 1.1.6 ?
- Use only public fields (private fields cannot be detected during annotation) that need to be serialized.
- Create a public constructor with no arguments for the annotation library.

**Comment by johncarl81** [comment]
Hi @doniwinata0309, could you produce a quick sample app to demonstrate the issue?  That would help me greatly in debugging.

**Comment by doniwinata0309** [comment]
sure, i will try to repro this from new project if possible.

By the way, after checking the build folder, i just found out that the nested @parcel class is not generated.
ex:
@Parcel
public class class1 {
 protected String id;
protected myInnerClass myClass2;

@parcel
public static class myInnerClass{
....
}
}

 Is this behaviour is expected ?

**Comment by johncarl81** [comment]
Nope, inner classes should ([and](https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/MultipleNullTest.java#L31) [do](https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/MutableLiveDataTest.java#L18)) work.

**Comment by johncarl81** [comment]
@doniwinata0309, still having issues with this?  If not, I'd like to close.

**Comment by doniwinata0309** [comment]
Yes we still facing the error, but i think we can close it for now. Aplogise for slow response. Thanks @johncarl81

**Comment by doniwinata0309** [comment]
By the way, do you have advice how to debugging the error ? I have no idea which file causing this null error. So far i know which module that causing the error, but it contains like hundred of classes with parceler annotation. It would be nice if we can pointing specific file that causing it.

**Comment by johncarl81** [comment]
quite alright... I dont know, but I've heard of similar problems recently in Kotlin... are you trying to set up an `@Parcel` on a sealed class?

**Comment by doniwinata0309** [comment]
Hi @johncarl81 , no we didn't use sealed class at all. I just checked my code, seems like it is different issue.

**Comment by doniwinata0309** [comment]
hi @johncarl81 , we have found 2 files that causing error. it is something like this:
`@Parcel
public class ExampleClass<T extends Serializable> {
    protected String titleExample;
    protected List<ParcelableClassExample<T>> testList;


    public List<ParcelableClassExample<T>> getChangeItems() {
        return null;
    }

    public void setChangeItems(List<ParcelableClassExample<T>> changeItems) {
        testList = changeItems;
    }

    public String getChangeTitle() {
        return titleExample;
    }

    public void setChangeTitle(String changeTitle) {
        titleExample = changeTitle;
    }
}
`
Do you know what might be wrong here ?
Removing list object will not causing error. I am still working to make sample,  don't know why it cannot be repro on the sample.

**Comment by johncarl81** [comment]
Ah, it's because Parceler doesn't know what to do with the generic type here... it's undefined in terms of this particular class.  Do you marshall (call Parcels.wrap/unwrap) `ExampleClass` directly or do you marshal subclasses of it?

**Comment by johncarl81** [comment]
Ah, interesting, it seems it's failing on lookup up the generic for the collection type:
```java
List<ParcelableClassExample<T>>
```
Now, I think this is something to fix...

**Comment by doniwinata0309** [comment]
Hi @johncarl81 , this object also causing the same error on our project
```List<T> itemList;```

**Comment by johncarl81** [comment]
For the time being, you can get around this issue by subclassing your class with generic parameters, specifying the concretes:
```java
@Parcel
public class StringExampleClass extends ExampleClass<String> {}
```

This has its limitations - particularly when dealing with multiple classes in an object graph.  But, I hope it would be a crutch for this issue until we can figure out a fix.

**Comment by doniwinata0309** [comment]
Thank for your suggestion @johncarl81 ! 
Will try wether we can pass specifying object or not in our case.
Hopefully it will fixed soon since we need to use AGP 3.3, it requires parceler 1.1.12 because of androidX migration. let me know if i can do something to help you.

**Comment by johncarl81** [comment]
If you could test a potential fix, I'd greatly appreciate it!  I hope to
spend some timr on it this weekend.

**Comment by doniwinata0309** [comment]
It is working perfectly @johncarl81 . i just trying your suggestion, so we put @parcel on subclass instead of the main class right ? so far it is good, but will need to test them on monday.

**Comment by doniwinata0309** [comment]
hi @johncarl81 , do you have plan to do fix about this issue ?
